#!/usr/bin/env bash

set -e

while getopts 'w:hv' opt; do
  case $opt in
    w)
      WORKSPACE={$opt}
      ;;
    h)
      echo "usage: ssh-run [-h] [-w workspace] host command"
      exit 1
      ;;
    v)
      set -x
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

shift $((OPTIND-1))

HOST="$1"
[ "$2" = '--' ] && COMMAND="${@:3}" || COMMAND="${@:2}"
LOCAL_DIR="$(pwd)/"
WORKSPACE=${WORKSPACE:-"~/.ssh-run"}
WORKSPACE_DIR="$WORKSPACE/$(basename $(pwd))/"
RSYNC_OPTS='--quiet --archive --compress'

# Ensure the workspace directory exists
ssh "$HOST" -- "mkdir -p $WORKSPACE"

# Copy the current directory to the remote workspace
rsync $RSYNC_OPTS --delete "$LOCAL_DIR" "$HOST:$WORKSPACE_DIR"

# Run the command inside the remote copy of the directory
ssh -qt "$HOST" -- "cd $WORKSPACE_DIR; $COMMAND"

# Copy any changes back to the local machine
rsync $RSYNC_OPTS "$HOST:$WORKSPACE_DIR" "$LOCAL_DIR"
